package dev.evoplus.setting

import dev.evoplus.setting.gui.SettingPalette
import gg.essential.elementa.utils.withAlpha
import java.awt.Color

object SettingConfig {

    // Old
    var brightDivider = Color(151, 151, 151)
    var divider = Color(80, 80, 80)
    var darkDivider = Color(50, 50, 50)
    var outline = Color(48, 48, 49)
    var scrollBar = Color(45, 45, 45)
    var brightHighlight = Color(50, 50, 50)
    var highlight = Color(33, 34, 38)
    var darkHighlight = Color(27, 28, 33)
    var lightBackground = Color(32, 32, 33)
    var background = Color(22, 22, 24)
    var darkBackground = Color(10, 10, 11)
    var searchBarBackground = Color(27, 28, 33)
    var brightText = Color(255, 255, 255)
    var midText = Color(187, 187, 187)
    var darkText = Color(119, 119, 121)
    var modalBackground = Color(0, 0, 0, 100)
    var warning = Color(239, 83, 80)
    var accent = Color(1, 165, 82)
    var success = Color(1, 165, 82)
    var transparent = Color(0, 0, 0, 0)
    var disabled = Color(80, 80, 80)

    // New
    var primary = Color(0x2997FF)
    var componentBorderDark = Color(0x000000)
    var midGray = Color(0x939393)
    var button = Color(0x323232)
    var buttonHighlight = Color(0x474747)
    var text = Color(0xBBBBBB)
    var textHighlight = Color(0xFFFFFF)
    var textDisabled = Color(0x6A6A6A)
    var textWarning = Color(0xF5534F)
    var textShadow = Color(0x161618)
    var textShadowLight = Color(0x3F3F3F)
    var textShadowMid = Color(0x232323)
    var componentBackground = Color(0x232323)
    var componentBackgroundHighlight = Color(0x2F2F2F)
    var componentBorder = Color(0x474747)
    var componentHighlight = Color(0x303030)
    var dividerDark = Color(0x232323)
    var scrollbar = Color(0x545454)
    var mainBackground = Color(0x1818180F, true)
    var textActive = Color(0x2997FF)
    var textActiveShadow = Color(0x0A253F)

    fun setAllInPalette() {
        SettingPalette.brightDividerState.set(brightDivider)
        SettingPalette.dividerState.set(divider)
        SettingPalette.darkDividerState.set(darkDivider)
        SettingPalette.outlineState.set(outline)
        SettingPalette.scrollBarState.set(scrollBar)
        SettingPalette.brightHighlightState.set(brightHighlight)
        SettingPalette.highlightState.set(highlight)
        SettingPalette.darkHighlightState.set(darkHighlight)
        SettingPalette.lightBackgroundState.set(lightBackground)
        SettingPalette.backgroundState.set(background)
        SettingPalette.darkBackgroundState.set(darkBackground)
        SettingPalette.searchBarBackgroundState.set(searchBarBackground)
        SettingPalette.brightTextState.set(brightText)
        SettingPalette.midTextState.set(midText)
        SettingPalette.darkTextState.set(darkText)
        SettingPalette.modalBackgroundState.set(modalBackground)
        SettingPalette.warningState.set(warning)
        SettingPalette.accentState.set(accent)
        SettingPalette.successState.set(success)
        SettingPalette.transparentState.set(transparent)
        SettingPalette.disabledState.set(disabled)
        SettingPalette.bgNoAlpha.set(background.withAlpha(0))

        SettingPalette.primary.set(primary)
        SettingPalette.componentBorderDark.set(componentBorderDark)
        SettingPalette.midGray.set(midGray)
        SettingPalette.button.set(button)
        SettingPalette.buttonHighlight.set(buttonHighlight)
        SettingPalette.text.set(text)
        SettingPalette.textHighlight.set(textHighlight)
        SettingPalette.textDisabled.set(textDisabled)
        SettingPalette.textWarning.set(textWarning)
        SettingPalette.componentBackground.set(componentBackground)
        SettingPalette.componentBackgroundHighlight.set(componentBackgroundHighlight)
        SettingPalette.componentBorder.set(componentBorder)
        SettingPalette.componentHighlight.set(componentHighlight)
        SettingPalette.dividerDark.set(dividerDark)
        SettingPalette.scrollbar.set(scrollbar)
        SettingPalette.textShadow.set(textShadow)
        SettingPalette.textShadowLight.set(textShadowLight)
        SettingPalette.textShadowMid.set(textShadowMid)
        SettingPalette.mainBackground.set(mainBackground)
        SettingPalette.textActive.set(textActive)
        SettingPalette.textActiveShadow.set(textActiveShadow)
    }
}
